name: ChatPlugin
main: de.johannes13.minecraft.bukkit.chat.plugin.ChatPlugin
version: 0.9
commands:
  me:
    description: sends a action to the current channel
    usage: |
           /<command> <message>
           Example: /<command> is playing Minecraft
  msg:
    description: 'sends a private message to a player'
    usage: |
           /<command> <player> <message>
           Example: /<command> Bukkit Great Job! - Sends the message "Great Job!" to Bukkit 
  ch:
    description: join a new channel or/and set your main channel
    usage: |
           /<command> [channel]
           Example: /<command> c - joins channel c
           Example: /<command> help for more detailed help on this command
  names:
    description: lists all player in the channel.
    usage: |
           /<command> [channel]
           Example: /<command> - Lists all players and irc users in your current channel
           Example: /<command> s - List all users in the channel s
  mme:
    description: sends a action to a player - /msg and /me in one command
    usage: |
           /<command> <player> <message>
           Example: /<command> SlowPlayer is waiting for you - Sends "* Player is waiting for you" to SlowPlayer 